apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    app: python
spec:
  containers:
  - name: pythonapi
    image: docker.io/stackrouteiac/pythonapi:v1
    env:
      - name:  MYSQL_HOSTNAME
        value: mysql
      - name:  MYSQL_PORT
        value: "3306"
      - name:  MYSQL_USER
        value: user
      - name:  MYSQL_PASSWORD
        value: pass
      - name:  MYSQL_DB
        value: myapp      
    ports:
    - containerPort: 8000
      name: api-port

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
    protocol: TCP
    port: 8000
    targetPort: api-port
